server_web/views.py
from flask import Blueprint,render_template, request, flash,redirect,url_for, Response
from flask_login import  login_required,  current_user
from . import db
from .models import Session as SessionUser, User, SessionMeta, Entrainement


from .classes.poseDetector.PoseDetector import  PoseDetector 



views = Blueprint('views', __name__)


def exercice(nom,niveau):
    if nom.lower() == "jambe":
        if niveau.lower() == "debutant":
            return  PoseDetector(0,"LEFT_HIP","LEFT_KNEE","LEFT_ANKLE",160,140)  
        elif niveau.lower() == "intermediaire":
            return  PoseDetector(0,"LEFT_HIP","LEFT_KNEE","LEFT_ANKLE",170,100)  
        else:
            return  PoseDetector(0,"LEFT_HIP","LEFT_KNEE","LEFT_ANKLE",170,80)  
    elif nom.lower() == "pompe":
        if niveau.lower() == "debutant":
            return  PoseDetector(0,"LEFT_SHOULDER","LEFT_ELBOW","LEFT_WRIST",160,90)  
        elif niveau.lower() == "intermediaire":
            return  PoseDetector(0,"LEFT_SHOULDER","LEFT_ELBOW","LEFT_WRIST",160,80)  
        else:
            return  PoseDetector(0,"LEFT_SHOULDER","LEFT_ELBOW","LEFT_WRIST",160,60)        
    pass
   

@views.route('/')
@login_required
def home():
   
          
    # sessionUser = SessionUser.query.filter_by(id_user=current_user.id, fini=False).all()
    q = db.session.query(
         SessionUser, SessionMeta, Entrainement
        ).join(User
               ).filter(
            User.id == SessionUser.id_user
            ).filter(
                SessionMeta.id_session == SessionUser.id
                ).filter(
                    Entrainement.id == SessionUser.id_entrainement
                    ).filter(
                        User.id == current_user.id,
                        SessionUser.fini == False
                        ).all()
    
    
    return render_template("home.html", user=current_user, information_user=q)



    """
    ici je tourne en boucle ma video 
    """
def gen(camera):
    condition = True
    while condition:
        frame = camera.get_frame()
        yield(b'--frame\r\n'
              b'Content-Type: image/jpeg\r\n\r\n'+ frame + b'\r\n\r\n')
        # if camera.getCounter() == camera.getNbrRepetition():       
        #     camera.setIsTerminate(True)
        if camera.getCounter() == camera.getNbrRepetition():       
            camera.setIsTerminate(True)

"""
    cette méthode me permet d'envoyer mon flux video dans une balise image que j'ai dans
    un template
"""
@views.route('/start-video', methods=['POST'])
def start_video():
    if request.method == 'POST':
        
        q = db.session.query(
            SessionUser, SessionMeta, Entrainement
                ).join(User
                    ).filter(
                    User.id == SessionUser.id_user
                    ).filter(
                        SessionMeta.id_session == SessionUser.id
                        ).filter(
                            Entrainement.id == SessionUser.id_entrainement
                            ).filter(
                                User.id == current_user.id,
                                SessionUser.fini == False
                                ).all()
        
        for row in q:
            
            if int(row[1].meta_value) == int(request.form.get('nombre_repetition')):
                data = {
                    'nombre_repetition' : row[1].meta_value,
                    'nom': row[2].nom,
                    'session_id' : row[0].id
                }
                print(data)
                # ici je lance ma camera et j'ini les exo
                global camera
                camera  = exercice(row[2].nom, row[2].niveau )
                print(f"global camera {camera}")
                return run_video(data)
            else:
                flash('mauvaises valeurs', category="error")
    return redirect(url_for('views.home'))

@views.route('/enregistrement')
def enregistrement():
    camera.__del__()
    return redirect(url_for('views.home'))

# la page où la vidéo se lance 
def run_video(data):
    #je compte les répétitions ici
    camera.setCounter(0)
    camera.setNbrRepetition(data['nombre_repetition'])
    
    return render_template('entrainement.html', user=current_user, data=data)


@views.route('/stop-video')
def stop_video():
    camera.__del__()
    return redirect(url_for('views.home'))



@views.route('/video')
@login_required
def video():

    return Response(gen(camera),
                    mimetype='multipart/x-mixed-replace; boundary=frame')
    

#ici je sauvegarde mes données dans ma db
@views.route('/save-exercice', methods=["POST"])
def save_exercice():
    if request.method =='POST':

        commentaire = request.form.get('formulaire')
        request_session = SessionUser.query.get(request.form.get('session_id'))
        if request_session == None:
            flash("Ne modifiez aucune donnée !", category="error") 

        elif len(commentaire ) <= 0:
            flash("le champ commentaire ne peut pas être vide.", category="error") 
        else:
            flash('Entraînement fini !', category="success")
            #ici je fais ma requêt pour sauvegarder mes exercices.
            request_session.fini = True
            request_session.message_user = commentaire
            request_session.repetition_fait = camera.getCounter()
            request_user = User.query.get(current_user.id)
            request_user.seance_restante -= 1
            db.session.commit()
            return stop_video()
    return resultat()
    
    #ici  on arrive sur la page résultat et je récupère les répétitions fais.
@views.route('/resultat', methods=["POST"])
@login_required
def resultat():
    
    data = {
        'repetition_fait': camera.getCounter(),
        'nombre_repetition_a_faire' : camera.getNbrRepetition(),
        'session_id'  : request.form.get('session_id')
    }
    camera.setIsTerminate(True)
    return render_template('resultat.html', user=current_user, data = data)

server_web/templates/entrainement.html
{% extends 'template.html' %}



{% block entrainement %}

<div class="container-fluid ">
    <h1> Renforcement musculaire : {{data['nom']}} </h1>
    <div class="accordion container d-flex justify-content-center" id="accordionExample">
        <div class="card">
            <div class="card-header" id="headingOne">
                <h2 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne"
                        aria-expanded="true" aria-controls="collapseOne">
                        Exemple de l'exercice
                    </button>
                </h2>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">
                    {% if data['nom'] == 'jambe' %}
                    <img src="{{url_for('static',filename="gif/squat-ex.gif")}}" alt="squat">
                    {% else %}
                    <img src="{{url_for('static',filename="gif/push-ex.gif")}}" alt="squat">

                    {% endif %}
                </div>
            </div>
        </div>


    </div>





    <div class="container d-flex justify-content-center ">
        <img src={{url_for('views.video')}}>
    </div>

    <div class="container">
        <form method="POST" action="{{url_for('views.resultat')}}">
            <input type="hidden" value={{data['session_id']}} id="session_id" name="session_id" />
            <input type="hidden" value="20" id="nombre_realise" name="nombre_realise" />

            <button type="submit" class="btn btn-primary mt-4  btn-lg btn-block">Finir</button>
        </form>
    </div>
    <div class="container">


        <button type="button" class="btn btn-warning  btn-lg btn-block mt-3"
            onclick="window.location.href='{{ url_for('views.stop_video') }}';">Stop</button>
    </div>
</div>

{% endblock entrainement %}

server_web/templates/home.html
{% extends 'template.html' %}


{% block board_patient %}




<div class="container">
    <div class="main-body mt-4">

        <h1 class="text-center">Fiche du patient</h1>

        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            {% if user.sexe %}
                            <img src="{{url_for('static',filename="femme-avatar.png")}}" alt="Admin"
                                class="rounded-circle" width="150">
                            {% else %}
                            <img src="{{url_for('static',filename="homme-avatar.png")}}" alt="Admin"
                                class="rounded-circle" width="150">
                            {% endif %}
                            <div class="mt-3">
                                <h4>{{user.nom}} {{user.prenom}}</h4>
                                {% if user.sexe %}
                                <p class="text-secondary mb-1">Femme</p>
                                {% else %}
                                <p class="text-secondary mb-1">Homme</p>

                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-8 ">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Nom Prénom</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{user.nom}} {{user.prenom}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Age</h6>
                            </div>
                            <div class="col-sm-5 text-secondary">
                                {{user.age}}
                            </div>

                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-5 text-secondary">
                                {{user.email}}
                            </div>

                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Pathologie</h6>
                            </div>
                            <div class="col-sm-5 text-secondary">
                                {% if user.pathologie == None %}
                                <span class="text-danger ">MANQUANTE</span>
                                {% else %}
                                {{user.pathologie}}
                                {% endif %}
                            </div>

                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Séances restantes</h6>
                            </div>
                            <div class="col-sm-5 text-secondary">
                                {{user.seance_restante}}
                            </div>


                        </div>
                        <hr>


                    </div>
                </div>


            </div>
            <div class="col-md-12">
                <h1>Exercice à réaliser</h1>
                <div class="accordion  " id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h5 class="mb-0">
                                <button class="btn btn-link" type="button" data-toggle="collapse"
                                    data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    Exercice
                                </button>
                            </h5>
                        </div>

                        {% if information_user|length > 0 %}

                        <div id="collapseOne" class="collapse show " aria-labelledby="headingOne"
                            data-parent="#accordionExample">
                            <div class="card-body ">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Partie du corps</th>

                                            <th scope="col">Niveau</th>
                                            <th scope="col">Répétition</th>
                                            <th scope="col">Commentaire</th>
                                            <th scope="col">Commencer</th>
                                        </tr>
                                    </thead>
                                    <tbody>


                                        {% for item in  information_user %}
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">{{item[2].nom}}</th>

                                            <th scope="col">{{item[2].niveau}}</th>
                                            <th scope="col">{{item[1].meta_value}}</th>
                                            <th scope="col">{{item[0].commentaire_kine}}</th>
                                            <th>
                                                <form method="post" action="{{ url_for('views.start_video') }}">
                                                    <input type="hidden" id="id_user" name="id_user"
                                                        value="{{current_user}}" />
                                                    <input type="hidden" id="nom_entrainement" name="nom_entrainement"
                                                        value="{{item[2].nom}}" />
                                                    <input type="hidden" id="nombre_repetition" name="nombre_repetition"
                                                        value="{{item[1].meta_value}}" />
                                                    <button type="submit" class="btn btn-success" id="btn_id_user">c'est
                                                        parti!</button>

                                                </form>

                                            </th>

                                        </tr>
                                        {% endfor %}



                                    </tbody>
                                </table>

                            </div>
                        </div>
                        {% else %}
                        <p class="h4 text-center"> Pas d'exercice pour l'instant !</p>
                        {% endif %}
                    </div>






                    {% endblock board_patient %}

server_web/templates/login.html
{% extends 'template.html' %}
{% block login %}
<div class="container">
  <div class="row gutters-sm">

    <div class="col-md-12 mb-3 mt-5">
      <div class="card">
        <div class="card-body">
          <div class="d-flex flex-column align-items-center text-center">
            <form method="POST">
              <h1> Connexion </h1>
              <div class="form-group">
                <label for="exampleInputEmail1 ">adresse email</label>
                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp"
                  placeholder="email">
              </div>


              <div class="form-group">
                <label for="exampleInputPassword1">Mot de passe</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="mot de passe">
              </div>

              <div class="form-group ">
                <button type="submit" class="btn btn-primary mt-4 ">Envoyer</button>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>

  </div>


  {% endblock login %}

server_web/templates/resultat.html
{% extends 'template.html' %}

{% block resultat %}

<ul class="list-group ">
    <li class="list-group-item text-center mt-5 h1">Répétitions réalisées : <span class="font-weight-bold">
            {{data['repetition_fait']}}</span>
        / {{data['nombre_repetition_a_faire']}}</li>


</ul>
<div class="container-fluid">
    <form method="POST" action="{{ url_for('views.save_exercice') }}">

        <div class="form-group">
            <label for="exampleFormControlTextarea1">Commentaire</label>
            <textarea class="form-control" id="formulaire" rows="3" name="formulaire"></textarea>
        </div>

        <div class="form-group">
            <input type="hidden" value={{data['session_id']}} id="session_id" name="session_id" />
            <button class="btn btn-primary" type="submit">Envoyer</button>
        </div>
    </form>
</div>

{% endblock resultat %}

server_web/templates/sign_up.html
{% extends 'template.html' %}
{% block sign_up %}


<div class="mt-4">

  <form method="POST" class="container-fluid w-25 ">
    <h1> Inscription </h1>



    <div class="form-group">
      <label for="nom">Nom</label>
      <input type="text" class="form-control" id="nom" name="nom" aria-describedby="emailHelp"
        placeholder="Entre un nom">
    </div>

    <div class="form-group">
      <label for="Prenom">Prenom</label>
      <input type="text" class="form-control" id="prenom" name="prenom" aria-describedby="emailHelp"
        placeholder="Entre un prenom">
    </div>


    <div class="form-group">
      <label for="email">adresse email</label>
      <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp"
        placeholder="Entre un email">
    </div>


    <div class="form-group">
      <label for="exampleInputPassword1">Mot de passe</label>
      <input type="password" class="form-control" id="password" name="password" placeholder="Entre un mot de passe">
    </div>


    <div class="form-group">
      <label for="exampleInputPassword2">Mot de passe(confirmé)</label>
      <input type="password" class="form-control" id="password2" name="password2" placeholder="Entre un mot de passe">
    </div>

    <div class="form-group">
      <label for="sexe">Choisi ton sexe</label>
      <select class="form-control" id="sexe" name="sexe">
        <option>Homme</option>
        <option>Femme</option>

      </select>
    </div>

    <button type="submit" class="btn btn-primary mt-4 d-flex">Envoyer</button>
  </form>

</div>
{% endblock sign_up %}

server_web/templates/start_video.html
{% extends 'template.html' %}
{% block start_video %}

<div class="container-fluid ">
    {{entrainement_information}}

    <h1>Entrainement </h1>
    {#
        <div class="container d-flex justify-content-center">
        <img src={{url_for('views.video')}}>
        <button type="button" class="btn btn-primary">Résultat</button>
        <button type="button" class="btn btn-warning">Recommencer</button>
    </div>
        
        #}
</div>


{% endblock start_video %}

server_web/templates/template.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

  <title>Flask apps</title>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <a class="navbar-brand mx-4 text-white " href="/">TakeCareMe</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link text-white" href="/">Acceuil</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link text-white" href="/logout">Déconnexion</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link text-white" href="/login">Connexion</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link text-white" href="/sign-up">Inscription</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endwith %}



  {% block login %}{% endblock login %}
  {% block sign_up %}{% endblock sign_up %}


  {% if user.is_authenticated %}

  {% block board_patient %}{% endblock board_patient %}
  {% block start_video %}{% endblock start_video %}
  {% block entrainement %}{% endblock entrainement %}
  {% block resultat %}{% endblock resultat %}
  {% endif %}








  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script src="{{ url_for('static', filename='index.js') }}"></script>
  <!-- Option 1: Bootstrap Bundle with Popper -->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>



  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>



</body>

</html>